### ISSUE TITLE
Multiple authors in bibtex

### ISSUE THREAD

**Issue by dsanson** [alejandrogallo/papis#38]
Currently, papis exports multiple authors as a list separated with commas, e.g.,

    { Barack Obama, Donald Trump }

But BibTeX doesn't understand this: it interprets commas as separating last name from first, and expects multiple authors to be separated by the word 'and'. So papis should export multiple authors either as,

    { Barack Obama and Donald Trump }

or

    { Obama, Barack and Trump, Donald }

**Comment by alejandrogallo** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

**Comment by alejandrogallo** [comment]
Hello and thanks for your interest!

**Comment by alejandrogallo** [comment]
I am going to close this and mark it as `faq` for further documentation usage.
Thanks for you time!
