### ISSUE TITLE
papis-python-rofi wrong name

### ISSUE THREAD

**Issue by nico202** [alejandrogallo/papis#43]
Hi, I could not open the issue on your python-rofi page because it's a fork.

the setup file has the line
>    name='python-rofi',

while in pip it is called  `papis-python-rofi`.
Could you update it in the repo (and tag the release?), else installing from github does not satifsy the dependency

Thanks

(info: I'm adding papis to nixpkgs (nix package manager))

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

**Comment by alejandrogallo** [comment]
Thanks for pointing this out, I fixed it now. The original project python-rofi seemed unmaintained
and that's why at some point I decided not to rely on them to add the features that
were missing to interface with rofi, at some point all will be unified into an organization account.

I have tagged the version 1.0.2 and updated in `pypi`, I hope this
solves the problem.

Nix package
-----------

Thanks a lot for that too!
If you'd like to add info about that in the section

```
doc/source/install.rst
```

of the documentation you're welcome! Also you can tell me what to write there
and I can add it myself.

Thank you!

**Comment by nico202** [comment]
Thanks, I'll open a PR when it'll be ready.
Here's the link to the nixpkgs PR in the meanwhile https://github.com/NixOS/nixpkgs/pull/34761.

**Comment by alejandrogallo** [comment]
Perfect! Thanks
